//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHotel1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryOfHotelNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryOfHotelNumber()
        {
            this.HotelNumber = new HashSet<HotelNumber>();
        }
    
        public int IdCategory { get; set; }
        public string NameOfCategory { get; set; }
        public int QuantityOfPlaces { get; set; }
        public int QuantityOfRooms { get; set; }
        public decimal CostPerDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelNumber> HotelNumber { get; set; }
    }
}
