//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHotel1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelNumber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelNumber()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int IdHotelNumber { get; set; }
        public string NameOfNumber { get; set; }
        public int IdCategory { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryOfHotelNumber CategoryOfHotelNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
