//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHotel1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.StatusNumber = new HashSet<StatusNumber>();
        }
    
        public int IdReservation { get; set; }
        public System.DateTime DateOfArrival { get; set; }
        public int IdHotelNumber { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual HotelNumber HotelNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusNumber> StatusNumber { get; set; }
    }
}
