//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHotel1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusNumber
    {
        public int IdStatusNumber { get; set; }
        public int IdEmployee { get; set; }
        public int IdReservation { get; set; }
        public System.DateTime DateOfArrival { get; set; }
        public System.DateTime DateOfLeaving { get; set; }
        public decimal FullCost { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
